package:
  name: pandas-datareader
  version: "0.2.0"

source:
  fn: pandas-datareader-0.2.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pandas-datareader/pandas-datareader-0.2.0.tar.gz
  md5: 25b40b0cd98f3956580a4f33aed2d56b
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pandas-datareader = pandas-datareader:main
    #
    # Would create an entry point called pandas-datareader that calls pandas-datareader.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pandas

  run:
    - python
    - pandas

test:
  # Python imports
  imports:
    - pandas_datareader
    - pandas_datareader.google
    - pandas_datareader.io
    - pandas_datareader.io.tests
    - pandas_datareader.yahoo

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - pytest

about:
  home: https://github.com/pydata/pandas-datareader
  license: BSD License
  summary: 'Data readers extracted from the pandas codebase,should be compatible with recent pandas versions'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
